import Link from 'next/link';

const F = "'Cormorant Garamond', Georgia, serif";

const Section = ({ title, children }: { title: string; children: React.ReactNode }) => (
  <div style={{ marginBottom: 44 }}>
    <p style={{ fontSize: 11, letterSpacing: 4, textTransform: 'uppercase', color: 'var(--text-dim)', margin: '0 0 16px 0', fontFamily: F }}>
      {title}
    </p>
    <div style={{ borderLeft: '1px solid var(--border)', paddingLeft: 20 }}>
      {children}
    </div>
  </div>
);

const P = ({ children }: { children: React.ReactNode }) => (
  <p style={{ fontSize: 15, lineHeight: 1.9, color: 'var(--text)', fontWeight: 300, fontFamily: F, margin: '0 0 12px 0' }}>
    {children}
  </p>
);

const Li = ({ children }: { children: React.ReactNode }) => (
  <li style={{ fontSize: 15, lineHeight: 1.9, color: 'var(--text)', fontWeight: 300, fontFamily: F, marginBottom: 6 }}>
    {children}
  </li>
);

export default function TermsPage() {
  return (
    <div style={{ minHeight: '100vh', background: 'var(--bg)', fontFamily: F, padding: '60px 28px 80px' }}>
      <div style={{ maxWidth: 620, margin: '0 auto' }}>

        <Link href="/" style={{ fontSize: 11, letterSpacing: 3, textTransform: 'uppercase', color: 'var(--text-muted)', textDecoration: 'none', display: 'inline-block', marginBottom: 48 }}>
          Back to BLUNNIT
        </Link>

        <h1 style={{ fontSize: 11, letterSpacing: 4, textTransform: 'uppercase', color: 'var(--text-dim)', margin: '0 0 8px 0', fontFamily: F, fontWeight: 400 }}>
          Terms of Service
        </h1>
        <p style={{ fontSize: 13, color: 'var(--text-muted)', margin: '0 0 48px 0', fontFamily: F, fontWeight: 300 }}>
          Last updated: April 2026
        </p>

        <Section title="What BLUNNIT Is">
          <ul style={{ margin: 0, paddingLeft: 20 }}>
            <Li>A self-awareness tool powered by AI.</Li>
            <Li>Not therapy, counseling, medical advice, or a mental health service.</Li>
            <Li>Not a substitute for professional care.</Li>
          </ul>
        </Section>

        <Section title="Eligibility">
          <P>You must be 18 years or older to use BLUNNIT. By creating an account you confirm you are 18 or older.</P>
        </Section>

        <Section title="AI Disclosure">
          <ul style={{ margin: 0, paddingLeft: 20 }}>
            <Li>All reflections are generated by artificial intelligence, not a human.</Li>
            <Li>The AI is not a licensed therapist, counselor, or professional of any kind.</Li>
            <Li>The AI may produce inaccurate, unhelpful, or incorrect responses.</Li>
            <Li>You are responsible for how you interpret and act on reflections.</Li>
          </ul>
        </Section>

        <Section title="Your Account">
          <ul style={{ margin: 0, paddingLeft: 20 }}>
            <Li>You are responsible for maintaining the security of your account.</Li>
            <Li>One account per person.</Li>
          </ul>
        </Section>

        <Section title="Subscriptions and Payments">
          <ul style={{ margin: 0, paddingLeft: 20 }}>
            <Li><strong>Free tier</strong>: limited reflections per week.</Li>
            <Li><strong>Full Access</strong>: $9.99/month, billed monthly through Stripe.</Li>
            <Li>Cancel anytime. Your access continues until the end of your billing period.</Li>
            <Li>No refunds for partial months.</Li>
          </ul>
        </Section>

        <Section title="Your Content">
          <ul style={{ margin: 0, paddingLeft: 20 }}>
            <Li>You own what you write.</Li>
            <Li>By using BLUNNIT, you grant us a license to use anonymized conversation data to improve AI quality.</Li>
            <Li>Personal identifiers are removed before any data is used for improvement.</Li>
            <Li>We never publish or share your personal reflections.</Li>
          </ul>
        </Section>

        <Section title="Intellectual Property">
          <ul style={{ margin: 0, paddingLeft: 20 }}>
            <Li>BLUNNIT, the BLUNNIT Protocol, the mirror system, and all associated branding are the intellectual property of Scott Stern.</Li>
            <Li>You may not copy, reproduce, or distribute the BLUNNIT Protocol or system.</Li>
          </ul>
        </Section>

        <Section title="Limitation of Liability">
          <ul style={{ margin: 0, paddingLeft: 20 }}>
            <Li>BLUNNIT is provided as-is.</Li>
            <Li>We are not liable for emotional distress, decisions made, relationships affected, or any outcomes resulting from use of the mirror.</Li>
            <Li>Use at your own discretion and responsibility.</Li>
          </ul>
        </Section>

        <Section title="Changes">
          <P>We may update these terms. Continued use after changes constitutes acceptance. We will note the date of the last update at the top of this page.</P>
        </Section>

        <p style={{ fontSize: 13, color: 'var(--text-muted)', fontFamily: F, fontWeight: 300, marginTop: 48, paddingTop: 24, borderTop: '1px solid var(--border)' }}>
          Questions? <a href="mailto:blunnit@gmail.com" style={{ color: 'var(--text-dim)' }}>blunnit@gmail.com</a>
        </p>
      </div>
    </div>
  );
}
